//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BingoCaller.rc
//
#define IDC_PRINT                       2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BINGOCALLER_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDB_BACKGROUND                  132
#define IDB_BITMAP_NUM_PANEL            144
#define IDD_DIALOG_PANEL                147
#define IDB_BITMAP_BLUE                 153
#define IDB_BITMAP_GOLD                 154
#define IDB_BITMAP_RED                  156
#define IDB_BITMAP_RED1                 157
#define IDB_BITMAP_BLUE1                158
#define IDB_BITMAP_GOLD1                159
#define IDB_BITMAP_CHECK_BUTTON         160
#define IDD_DIALOG_SELECT_COLOR         161
#define IDD_DIALOG_USER_SCREEN          163
#define IDC_STATIC_ACTIONS              1000
#define IDC_STATIC_CALL_NUMBER          1001
#define IDC_STATIC_NUMBERS_CALLED       1002
#define IDC_STATIC_CHECK_WINNER         1003
#define IDC_EDIT1                       1004
#define IDC_BUTTON_CHECK                1005
#define IDC_EDIT_LAST_MATCHED           1006
#define IDC_EDIT_HOUSE_MATCHED          1007
#define IDC_EDIT_ONE_LINE               1009
#define IDC_EDIT_TWO_LINE               1010
#define IDC_EDIT_TWO_LINE2              1011
#define IDC_EDIT_FULL_HOUSE             1011
#define IDC_EDIT_RANGE_FROM             1013
#define IDC_EDIT_RANGE_TO               1014
#define IDC_EDIT_ONE_LINE_MISS          1015
#define IDC_BUTTON_SET_RANGE            1016
#define IDC_EDIT_TWO_LINE_MISS          1017
#define IDC_EDIT_FULL_HOUSE_MISS        1018
#define IDC_STATIC_RESULT               1019
#define IDC_STATIC_RANGE                1020
#define IDC_STATIC_ONE_LINE_MATCH       1021
#define IDC_STATIC_ONE_LINE_MISS        1022
#define IDC_STATIC_TWO_LINE_MATCH       1023
#define IDC_STATIC_FULL_HOUSE_MATCH     1024
#define IDC_STATIC_TWO_LINE_MISS        1025
#define IDC_STATIC_FULL_HOUSE_MISS      1026
#define IDC_STATIC_NUMBERS_PANEL        1027
#define IDC_STATIC_CALLED_NUMBER_SHOW   1029
#define IDC_STATIC_NUMBERS_CALLED_SHOW  1030
#define IDC_STATIC_LAST_CALLED_STRING_BOX 1031
#define IDC_STATIC_CALLED_COUNT_STRING_BOX 1032
#define IDC_CHECK_ONELINE               1033
#define IDC_CHECK_TWOLINE               1034
#define IDC_STATIC_VERIFY_WINNER_STR_BOX 1035
#define IDC_STATIC_SET_RANGE_STR_BOX    1036
#define IDC_STATIC_ONE_LINE_CHECK       1037
#define IDC_STATIC_WINNING_PATTERNS     1038
#define IDC_STATIC_TWO_LINE_CHECK       1039
#define IDC_STATIC_GAME_NUMBER          1040
#define IDC_STATIC_GAME_COLOR           1041
#define IDC_STATIC_GAME_NUMBER_PAD      1042
#define IDC_STATIC_COLOR_PAD            1043
#define IDC_STATIC_GOLD                 1043
#define IDC_STATIC_PURPLE               1044
#define IDC_EDIT_LOGO_FILE              1044
#define IDC_STATIC_YELLOW               1045
#define IDC_BUTTON_LOGO                 1045
#define IDC_STATIC_PINK                 1046
#define IDC_EDIT_AD_FILE                1046
#define IDC_STATIC_GREEN                1047
#define IDC_BUTTON_ADVERTISE            1047
#define IDC_STATIC_ORANGE               1048
#define IDC_EDIT_ADVERTISE_TEXT         1048
#define IDC_STATIC_BLUE                 1049
#define IDC_STATIC_CHOOSE_LOGO          1049
#define IDC_STATIC_RED                  1050
#define IDC_STATIC_CHOOSE_AD            1050
#define IDC_STATIC_LILAC                1051
#define IDC_BUTTON2                     1051
#define IDC_BUTTON_AD_TEXT_SET          1051
#define IDC_STATIC_BROWN                1052
#define IDC_BUTTON_AD_IMAGE_REMOVE      1052
#define IDC_STATIC_WHITE                1053
#define IDC_STATIC_SILVER               1054
#define IDC_COMBO_SESSION_NAME          1054
#define IDC_STATIC_LIGHT_RED            1055
#define IDC_STATIC_SESSION_NAME         1055
#define IDC_STATIC_DARK_RED             1056
#define IDC_STATIC_NAME                 1056
#define IDC_STATIC_LIGHT_GREEN          1057
#define IDC_STATIC_DARK_GREEN           1058
#define IDC_STATIC_LIGHT_BLUE           1059
#define IDC_STATIC_DARK_BLUE            1060
#define IDC_STATIC_LIGHT_YELLOW         1061
#define IDC_STATIC_DARK_YELLOW          1062
#define IDC_STATIC_LIGHT_ORANGE         1063
#define IDC_STATIC_DARK_ORANGE          1064
#define IDC_STATIC_LIGHT_PURPLE         1065
#define IDC_STATIC_DARK_PURPLE          1066
#define IDC_STATIC_LIGHT_GREY           1067
#define IDC_STATIC_DARK_GREY            1068
#define IDC_STATIC_LIGHT_BROWN          1069
#define IDC_STATIC_DARK_BROWN           1070
#define IDC_STATIC_LIGHT_PINK           1071
#define IDC_STATIC_DARK_RED2            1072
#define IDC_STATIC_DARK_PINK            1072

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
